# Generated by Django 5.2.4 on 2025-07-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='questions_json',
            field=models.JSONField(),
        ),
    ]
